/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  /*
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  */

  // But you can create a sidebar manually

  tutorialSidebar: [
    {type: 'doc', id: 'intro'},
    {
      type: 'category',
      label: 'Installation',
      items: [
        {type: 'doc', id: 'installation/requirements'},
        {type: 'doc', id: 'installation/install-xcp-ng'},
        {type: 'doc', id: 'installation/migrate-to-xcp-ng'},
        {type: 'doc', id: 'installation/upgrade'},
      ],
    },
    {
      type: 'category',
      label: 'Releases',
      items: [
          {type: 'doc', id: 'releases/release-8-3'},
          {type: 'doc', id: 'releases/release-8-2'},
      ],
    },
    {
      type: 'category',
      label: 'Management and Backup',
      items: [
        {
          type: 'category',
          label: 'Local Management',
          items: [
              {type: 'doc', id: 'management/manage-locally/xo-lite'},
              {type: 'doc', id: 'management/manage-locally/api'},
              {type: 'doc', id: 'management/manage-locally/cli'},
          ],
        },
        {
          type: 'category',
          label: 'Manage at scale',
          items: [
            {type: 'doc', id: 'management/manage-at-scale/xo-web-ui'},
            {type: 'doc', id: 'management/manage-at-scale/xo-cli'},
            {type: 'doc', id: 'management/manage-at-scale/xo-api'},
          ],
        },
        {type: 'doc', id: 'management/updates'},
        {type: 'doc', id: 'management/additional-packages'},
        {type: 'doc', id: 'management/backup'},
        {type: 'doc', id: 'management/cloud'},
        {type: 'doc', id: 'management/ha'},
        {type: 'doc', id: 'management/infrastructure-as-code'},
        {type: 'doc', id: 'management/vm-load-balancing'},
      ],
    },
    {
      type: 'doc',
      id: 'vms/vms',
    },
    {
      type: 'doc',
      id: 'storage/storage',
    },
    {
      type: 'doc',
      id: 'networking/networking',
    },
    {
      type: 'doc',
      id: 'compute',
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        { type: 'doc', id: 'guides/TLS-certificates-xcpng' },
        { type: 'doc', id: 'guides/VLAN-trunking-vm' },
        { type: 'doc', id: 'guides/autostart-vm' },
        { type: 'doc', id: 'guides/create-use-custom-xcpng-ubuntu-templates' },
        { type: 'doc', id: 'guides/dom0-memory' },
        { type: 'doc', id: 'guides/guest-UEFI-Secure-Boot' },
        { type: 'doc', id: 'guides/host-reboot' },
        { type: 'doc', id: 'guides/logs' },
        { type: 'doc', id: 'guides/pfsense' },
        { type: 'doc', id: 'guides/shrink_virtual_drive' },
        { type: 'doc', id: 'guides/software-RAID-SR' },
        { type: 'doc', id: 'guides/xcpng-in-a-vm' },
      ],
    },
    {
      type: 'doc',
      id: 'xostor/xostor',
    },
    {
      type: 'category',
      label: 'Troubleshooting',
      items: [
        { type: 'doc', id: 'troubleshooting/after-upgrade' },
        { type: 'doc', id: 'troubleshooting/common-problems' },
        { type: 'doc', id: 'troubleshooting/installation-upgrade' },
        { type: 'doc', id: 'troubleshooting/log-files' },
        {
          type: 'category',
          label: 'Storage',
          items: [
            { type: 'doc', id: 'troubleshooting/storage/disappearing-NVMe-drives' },
            { type: 'doc', id: 'troubleshooting/storage/disk-failure-softwaire-RAID' },
            { type: 'doc', id: 'troubleshooting/storage/iscsi-troubleshooting' },
          ],
        },
        { type: 'doc', id: 'troubleshooting/windows-pv-tools' },
      ]
    },
    {
      type: 'category',
      label: 'Project',
      items: [
        {
          type: 'category',
          label: 'Development Process',
          items: [
            { type: 'doc', id: 'project/development-process/what-xcp-ng-is-made-of'},
            { type: 'doc', id: 'project/development-process/release-process-overview'},
            { type: 'doc', id: 'project/development-process/development'},
            { type: 'doc', id: 'project/development-process/tags-maintenance-branches-in-our-code'},
            { type: 'doc', id: 'project/development-process/rpm-packaging'},
            { type: 'doc', id: 'project/development-process/build-system'},
            { type: 'doc', id: 'project/development-process/local-rpm-build'},
            { type: 'doc', id: 'project/development-process/local-xapi-build'},
            { type: 'doc', id: 'project/development-process/kernel-module-policy'},
            { type: 'doc', id: 'project/development-process/ISO-modification'},
            { type: 'doc', id: 'project/development-process/commit-message-conventions'},
            { type: 'doc', id: 'project/development-process/tests'},
            { type: 'doc', id: 'project/development-process/koji-initial-setup'},
            { type: 'doc', id: 'project/development-process/performance-tests'},
          ],
        },
        { type: 'doc', id: 'project/about'},
        { type: 'doc', id: 'project/architecture'},
        { type: 'doc', id: 'project/contributing'},
        { type: 'doc', id: 'project/ecosystem'},
        { type: 'doc', id: 'project/gitrepo'},
        { type: 'doc', id: 'project/licenses'},
        { type: 'doc', id: 'project/mirrors'},
        { type: 'doc', id: 'project/roadmap'},
        { type: 'doc', id: 'project/security'},
      ],
    },
    {
      type: 'category',
      label: 'Appendix',
      items: [
        { type: 'doc', id: 'appendix/answerfile'},
        { type: 'doc', id: 'appendix/cli_reference'},
        { type: 'doc', id: 'appendix/glossary'},
      ]
    }
  ],
};

export default sidebars;