---
name: Linting
on: [push]

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Style
        uses: xcp-ng/vale-styles@v0.1
        with:
          files: docs/*
